export const storefrontCopy = {
    en: {
        pageTitle: 'Menu',
        tagline: 'Turkish street kitchen',
        order: 'Your order',
        eyebrow: 'Made fresh to order',
        heading: 'Our menu',
        oneItem: 'item',
        manyItems: 'items',
        categories: 'Product categories',
        all: 'All',
        products: 'Products',
        addToCart: 'Add to cart',
        emptyTitle: 'No dishes here yet',
        emptyText: 'Choose another category to keep browsing.',
        language: 'Language',
    },
    tr: {
        pageTitle: 'Menü',
        tagline: 'Türk sokak mutfağı',
        order: 'Siparişiniz',
        eyebrow: 'Sipariş üzerine taze hazırlanır',
        heading: 'Menümüz',
        oneItem: 'ürün',
        manyItems: 'ürün',
        categories: 'Ürün kategorileri',
        all: 'Tümü',
        products: 'Ürünler',
        addToCart: 'Sepete ekle',
        emptyTitle: 'Burada henüz ürün yok',
        emptyText: 'Başka bir kategori seçin.',
        language: 'Dil',
    },
    de: {
        pageTitle: 'Speisekarte',
        tagline: 'Türkische Straßenküche',
        order: 'Deine Bestellung',
        eyebrow: 'Frisch auf Bestellung',
        heading: 'Unsere Speisekarte',
        oneItem: 'Artikel',
        manyItems: 'Artikel',
        categories: 'Produktkategorien',
        all: 'Alle',
        products: 'Produkte',
        addToCart: 'In den Warenkorb',
        emptyTitle: 'Hier gibt es noch keine Gerichte',
        emptyText: 'Wähle eine andere Kategorie aus.',
        language: 'Sprache',
    },
} as const;

export type SupportedLocale = keyof typeof storefrontCopy;
