export const storefrontCopy = {
    en: {
        pageTitle: 'Menu',
        tagline: 'Turkish street kitchen',
        order: 'Your order',
        eyebrow: 'Made fresh to order',
        heading: 'Our menu',
        oneItem: 'item',
        manyItems: 'items',
        categories: 'Product categories',
        all: 'All',
        products: 'Products',
        addToCart: 'Add to cart',
        cartTitle: 'Your order',
        cartDescription: 'Review and adjust your order.',
        cartEmpty: 'Your cart is empty.',
        cartEmptyText: 'Add something from the menu to get started.',
        closeCart: 'Close cart',
        decreaseQuantity: 'Decrease quantity',
        increaseQuantity: 'Increase quantity',
        remove: 'Remove',
        total: 'Total',
        checkout: 'Checkout',
        checkoutEyebrow: 'Complete your order',
        checkoutHeading: 'Checkout',
        backToMenu: 'Back to menu',
        fulfillmentMethod: 'Delivery or pickup',
        delivery: 'Delivery',
        deliveryDescription: '€3 delivery, free for orders from €25.',
        pickup: 'Pickup',
        pickupDescription: 'Collect your order at Köz Kebab.',
        contactDetails: 'Contact details',
        fullName: 'Full name',
        email: 'Email address',
        phone: 'Phone number',
        deliveryAddress: 'Delivery address',
        streetAddress: 'Street and house number',
        postcode: 'Postcode',
        city: 'City',
        orderNotes: 'Order notes',
        orderNotesPlaceholder: 'Allergies or preparation requests',
        paymentMethod: 'Payment method',
        cash: 'Cash',
        cashDescription: 'Pay in cash when you receive your order.',
        placeOrder: 'Place order',
        placingOrder: 'Placing order…',
        confirmationPageTitle: 'Order confirmed',
        confirmationEyebrow: 'Order received',
        confirmationHeading: 'Thank you for your order',
        confirmationText:
            'We have received your order and will start preparing it shortly.',
        returnToMenu: 'Return to menu',
        orderSummary: 'Order summary',
        subtotal: 'Subtotal',
        shipping: 'Delivery',
        free: 'Free',
        emptyTitle: 'No dishes here yet',
        emptyText: 'Choose another category to keep browsing.',
        language: 'Language',
    },
    tr: {
        pageTitle: 'Menü',
        tagline: 'Türk sokak mutfağı',
        order: 'Siparişiniz',
        eyebrow: 'Sipariş üzerine taze hazırlanır',
        heading: 'Menümüz',
        oneItem: 'ürün',
        manyItems: 'ürün',
        categories: 'Ürün kategorileri',
        all: 'Tümü',
        products: 'Ürünler',
        addToCart: 'Sepete ekle',
        cartTitle: 'Siparişiniz',
        cartDescription: 'Siparişinizi gözden geçirin ve düzenleyin.',
        cartEmpty: 'Sepetiniz boş.',
        cartEmptyText: 'Başlamak için menüden bir ürün ekleyin.',
        closeCart: 'Sepeti kapat',
        decreaseQuantity: 'Adedi azalt',
        increaseQuantity: 'Adedi artır',
        remove: 'Kaldır',
        total: 'Toplam',
        checkout: 'Ödeme',
        checkoutEyebrow: 'Siparişinizi tamamlayın',
        checkoutHeading: 'Ödeme',
        backToMenu: 'Menüye dön',
        fulfillmentMethod: 'Teslimat veya gel-al',
        delivery: 'Teslimat',
        deliveryDescription: 'Teslimat €3, €25 ve üzeri siparişlerde ücretsiz.',
        pickup: 'Gel-al',
        pickupDescription: 'Siparişinizi Köz Kebab’dan teslim alın.',
        contactDetails: 'İletişim bilgileri',
        fullName: 'Ad soyad',
        email: 'E-posta adresi',
        phone: 'Telefon numarası',
        deliveryAddress: 'Teslimat adresi',
        streetAddress: 'Sokak ve bina numarası',
        postcode: 'Posta kodu',
        city: 'Şehir',
        orderNotes: 'Sipariş notları',
        orderNotesPlaceholder: 'Alerjiler veya hazırlama istekleri',
        paymentMethod: 'Ödeme yöntemi',
        cash: 'Nakit',
        cashDescription: 'Siparişinizi teslim alırken nakit ödeyin.',
        placeOrder: 'Sipariş ver',
        placingOrder: 'Sipariş veriliyor…',
        confirmationPageTitle: 'Sipariş onaylandı',
        confirmationEyebrow: 'Sipariş alındı',
        confirmationHeading: 'Siparişiniz için teşekkürler',
        confirmationText:
            'Siparişinizi aldık ve kısa süre içinde hazırlamaya başlayacağız.',
        returnToMenu: 'Menüye dön',
        orderSummary: 'Sipariş özeti',
        subtotal: 'Ara toplam',
        shipping: 'Teslimat',
        free: 'Ücretsiz',
        emptyTitle: 'Burada henüz ürün yok',
        emptyText: 'Başka bir kategori seçin.',
        language: 'Dil',
    },
    de: {
        pageTitle: 'Speisekarte',
        tagline: 'Türkische Straßenküche',
        order: 'Deine Bestellung',
        eyebrow: 'Frisch auf Bestellung',
        heading: 'Unsere Speisekarte',
        oneItem: 'Artikel',
        manyItems: 'Artikel',
        categories: 'Produktkategorien',
        all: 'Alle',
        products: 'Produkte',
        addToCart: 'In den Warenkorb',
        cartTitle: 'Deine Bestellung',
        cartDescription: 'Prüfe und bearbeite deine Bestellung.',
        cartEmpty: 'Dein Warenkorb ist leer.',
        cartEmptyText: 'Füge ein Gericht aus der Speisekarte hinzu.',
        closeCart: 'Warenkorb schließen',
        decreaseQuantity: 'Menge verringern',
        increaseQuantity: 'Menge erhöhen',
        remove: 'Entfernen',
        total: 'Gesamt',
        checkout: 'Zur Kasse',
        checkoutEyebrow: 'Bestellung abschließen',
        checkoutHeading: 'Zur Kasse',
        backToMenu: 'Zurück zur Speisekarte',
        fulfillmentMethod: 'Lieferung oder Abholung',
        delivery: 'Lieferung',
        deliveryDescription: '3 € Lieferung, ab 25 € Bestellwert kostenlos.',
        pickup: 'Abholung',
        pickupDescription: 'Hole deine Bestellung bei Köz Kebab ab.',
        contactDetails: 'Kontaktdaten',
        fullName: 'Vollständiger Name',
        email: 'E-Mail-Adresse',
        phone: 'Telefonnummer',
        deliveryAddress: 'Lieferadresse',
        streetAddress: 'Straße und Hausnummer',
        postcode: 'Postleitzahl',
        city: 'Ort',
        orderNotes: 'Bestellhinweise',
        orderNotesPlaceholder: 'Allergien oder Zubereitungswünsche',
        paymentMethod: 'Zahlungsart',
        cash: 'Barzahlung',
        cashDescription: 'Bezahle bar, wenn du deine Bestellung erhältst.',
        placeOrder: 'Bestellung aufgeben',
        placingOrder: 'Bestellung wird aufgegeben…',
        confirmationPageTitle: 'Bestellung bestätigt',
        confirmationEyebrow: 'Bestellung eingegangen',
        confirmationHeading: 'Vielen Dank für deine Bestellung',
        confirmationText:
            'Wir haben deine Bestellung erhalten und beginnen in Kürze mit der Zubereitung.',
        returnToMenu: 'Zur Speisekarte',
        orderSummary: 'Bestellübersicht',
        subtotal: 'Zwischensumme',
        shipping: 'Lieferung',
        free: 'Kostenlos',
        emptyTitle: 'Hier gibt es noch keine Gerichte',
        emptyText: 'Wähle eine andere Kategorie aus.',
        language: 'Sprache',
    },
} as const;

export type SupportedLocale = keyof typeof storefrontCopy;
